### ISSUE TITLE
Would you help me with your script?

### ISSUE THREAD

**Issue by Gadwen** [gormlabenz/gaugan2-renderer#1]
Hi.
I hope this is the right place to contact you. At first a big thank you for writing this script. I am using GauGan for Art. I am very interested in using your script because it would make it much easier for me to automate the uploading process. The only problem is that I have absolutely no experience in Python. Working on Windows. I have Python installed and I managed to download your script.
Could you give me a hint how to use it? I know how to open the python console.

I tried to start the script with the command “main.py” I get this:
..\gaugan2_renderer.py", line 5, in <module>
import imageio
ModuleNotFoundError: No module named 'imageio'

When I try “gaugan2_renderer.py” I get the same:
..\gaugan2_renderer.py", line 5, in <module>
import imageio
ModuleNotFoundError: No module named 'imageio'

Under the ReadMe you write: “Clone this repository and import the Gaugan2Renderer from gaugan2_renderer” If this is an important step I need to do, could you tell me how to do that? As I understand cloning the repository in my case is downloading and unpacking the Zip. So that is done. How do I import the Gaugan2Renderer from gaugan2_renderer?
After that do I have to create 2 folders with the names “input_folder” and “output_folder”?
I would be very thankful if you could help me getting your script to work. I hope this is not bothering you too much.

**Comment by gormlabenz** [comment]
Hello,
It looks like you don't have installed the requirements. To do this, navigate in the console inside the folder you have downloaded and run the comand `pip install -r requirements.txt`. I also recomment the usage of virtual envirements. Take a look here: https://www.youtube.com/watch?v=APOPm01BVrk&t=820s
I also updated the readme to answer your other questions. (and also the code, so you should redownload this repository)

**Comment by Gadwen** [comment]
Now it works! 

That was a fast reply. Thank you. In the last view hours, I tried to get the script to work. No luck. I ran into all sorts of errors about not being "able to write this and that", so I cleaned my system from old python installations and started a new installation. Now running Python 3.10.2. I followed all the steps you suggested. But… Nothing in the “output_folder”. Now revealing my big mistake… drumroll… I saved the segmentation map as *.jpg! Not as *.png. 
Again. A big THANK YOU for your help and the script. If I could, I would buy you a coffee or beer. 

Perhaps you would like to point out that you, OF COURSE, need to use a *png. 

Thx

**Comment by gormlabenz** [comment]
Glad to here! 
If you like, you can buy me a coffee! Here is the url: https://www.buymeacoffee.com/gormlabenz
I would also like to see results you made with the skript, I could also link them in the README. 
I'll add the item to the README, thanks for that!

**Comment by Gadwen** [comment]
Would love to but buymeacoffee.com only takes credit cards. Sadly, that is no option for me. If there is any other way through PayPal for example, please let me now. I will absolutely let you know with what we come up. It will take some time though. Now with this option in our hands we are probably going to change the whole workflow with much more time for the creative part. Thanks again.
