### ISSUE TITLE
How to set the text ?

### ISSUE THREAD

**Issue by valentingillet** [gormlabenz/gaugan2-renderer#4]
Hey, I have been trying to add text as as input but can't seem to make it work for some reason, here is what I tried:
within def close_popups I added :

  activate_text_input = self.driver.find_element(
            By.XPATH, '//*[@id="enable_text"]')
        if activate_text_input:
            activate_text_input.click()

and then added :

  def type_text(self):
        type_input = self.driver.find_element(
By.CSS_SELECTOR,"#text_input")
        if type_input:
            type_input.send_keys("landscape at midnight")

the script runs but it bypasses the text input everytime, do you have any idea why ?

best !

**Comment by houseofc** [comment]
Do it in run instead. Here are some functions that will make setting options easier:

def checkOn(self,id):
        box = self.driver.find_element(
            By.XPATH, '//*[@id= "' + id + '"]')
        if not box.get_attribute('checked') :
            box.click()

def checkOff(self,id):
       box = self.driver.find_element(
            By.XPATH, '//*[@id= "' + id + '"]')
        if box.get_attribute('checked') :
            [box.click](http://box.click/)()

def setValue(self,id,val):
        self.driver.find_element(
            By.XPATH, '//*[@id="'+id+'"]').clear().send_keys(val)
        time.sleep(self.waiting_time)

Put your text in self.text (you can pass it on the command line)

Then add the following somewhere in run (you can do it before iterating through the files):
self.checkOn('enable_text')
self.setValue('text_input',self.text)

**Comment by houseofc** [comment]
Alternately (if you get a "not interactable") this way will also work

def setValue(self,id,val):
    self.driver.execute_script("document.getElementById('"+id+"').value ='"+val+"';")
